name: Release New data-store Version
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  new_version_release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'misc/version-')
    runs-on: ubuntu-latest

    permissions: 
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build new version for Linux
      id: build_step
      working-directory: ./data-store
      run: |
        version_str=$(perl -nle 'print $1 if /Version = "([^"]+)"/' "version.go")
        file="data-store-v${version_str}-linux-amd64"
        echo "Building the binary for Linux with version $version_str"
        env GOOS=linux GOARCH=amd64 go build ./... -o $file
        echo "Binary $file created. Moving it to the $HOME directory"
        mv $file $HOME/$file
        echo "version_str=$version_str" >> $GITHUB_OUTPUT
        echo "file=$file" >> $GITHUB_OUTPUT
    
    - name: Create new release
      id: release_step
      working-directory: ./data-store
      run: |
        version_str="${{ steps.build_step.outputs.version_str }}"
        file="$HOME/${{ steps.build_step.outputs.file }}"
        echo "Creating a new release for version $version_str"
        gh release create "v${version_str}" $file --title "Release v${version_str}" --generate-notes --target main
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
